# Generated by Django 3.0.3 on 2020-02-25 11:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('travels', '0003_auto_20200225_1532'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Destinations',
            new_name='Destination',
        ),
    ]
