# Generated by Django 3.0.3 on 2020-02-25 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travels', '0002_destinations_offer'),
    ]

    operations = [
        migrations.AddField(
            model_name='destinations',
            name='Duration',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='destinations',
            name='price',
            field=models.IntegerField(default=50),
            preserve_default=False,
        ),
    ]
