# Generated by Django 3.0.3 on 2020-02-25 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travels', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='destinations',
            name='offer',
            field=models.BooleanField(default=False),
        ),
    ]
